boms:
  - groupId: androidx.compose
    artifactId: compose-bom
    versions:
      - 2023.01.00
      - 2023.03.00
      - 2023.04.01
      - 2023.05.01
      - 2023.06.01
      - 2023.08.00
      - 2023.09.02
      - 2023.10.01
      - 2024.01.00
      - 2024.02.02
      - 2024.03.00
      - 2024.04.01
      - 2024.05.00
      - 2024.06.00
      - 2024.09.03
      - 2024.10.01
      - 2024.11.00
      - 2024.12.01
    
  - groupId: com.google.firebase
    artifactId: firebase-bom
    versions:
      - 31.0.0
      - 31.1.0
      - 31.2.0
      - 31.3.0
      - 31.4.0
      - 31.5.0
      - 32.0.0
      - 32.1.0
      - 32.2.0
      - 32.3.1
      - 32.4.0
      - 32.5.0
      - 32.6.0
      - 32.7.0
      - 32.8.0
      - 33.0.0
      - 33.1.0
      - 33.2.0
      - 33.3.0
      - 33.4.0
      - 33.5.1
      - 33.6.0

settings:
  mavenRepository: https://maven.google.com/
  snapshotDirectory: ./snapshots
  cacheEnabled: true