boms:
  - groupId: androidx.compose
    artifactId: compose-bom
  - groupId: com.google.firebase
    artifactId: firebase-bom

settings:
  mavenRepository: https://maven.google.com/
  snapshotDirectory: ./snapshots
  cacheEnabled: true
