services:
  # Development server
  dev:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - NODE_ENV=development
  
  # Production preview
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./docs:/usr/share/nginx/html:ro
    command: >
      sh -c "echo 'Starting BOM Mapping UI at http://localhost:8080' && nginx -g 'daemon off;'"