name: Update BOM Data

on:
  schedule:
    # 毎週月曜日の午前3時（UTC）に実行
    - cron: '0 3 * * 1'
  
  # 手動実行のためのトリガー
  workflow_dispatch:
    inputs:
      force:
        description: 'キャッシュを無視して強制的に再生成する'
        required: false
        default: 'false'
        type: boolean
      specific_bom:
        description: '特定のBOMのみを更新する（artifactId）'
        required: false
        type: string

jobs:
  update-bom-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: チェックアウト
        uses: actions/checkout@v4
      
      - name: JDKセットアップ
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Gradleキャッシュ
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      - name: BOMデータ生成
        run: |
          ARGS="generate --parallel"
          
          # 特定のBOMが指定された場合
          if [ -n "${{ github.event.inputs.specific_bom }}" ]; then
            ARGS="$ARGS --bom=${{ github.event.inputs.specific_bom }}"
          fi
          
          # 強制再生成が指定された場合
          if [ "${{ github.event.inputs.force }}" == "true" ]; then
            ARGS="$ARGS --force"
          fi
          
          # BOMデータ生成コマンド実行
          ./gradlew run --args="$ARGS"
      
      - name: 変更の確認
        id: check_changes
        run: |
          git add docs/data snapshots
          # 変更があるかチェック
          if git diff --staged --quiet; then
            echo "変更はありません"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "変更が検出されました"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
      
      - name: 変更をコミット
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          
          git commit -m "chore(data): BOMデータを更新 [GitHub Actions]"
      
      - name: 変更をプッシュ
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}